### ISSUE TITLE
Query: Regarding the installed packages

### ISSUE THREAD

**Issue by giriannamalai** [Salamek/chromium-kiosk#24]
I have seen that zeromq and celery libraries were installed during kiosk setup. 
I could not find related code in Repo. 
May I know the reason?

**Comment by Salamek** [comment]
@giriannamalai zeromq will be depedency of websockets i guess (websockets are used to notify browser extension about changes in config.yml)

from where is `celery` coming from i have no idea... try to run `pacman -Qi celery` to check "Required-By" field pls

**Comment by giriannamalai** [comment]
Yes. Thank you.
