### ISSUE TITLE
Update Arch repo pkg to work with Python3.10

### ISSUE THREAD

**Issue by pszafer** [Salamek/chromium-kiosk#28]
after update Arch to python3.10 your package is not working anymore:
```
 Traceback (most recent call last):
   File "/usr/bin/chromium-kiosk", line 33, in <module>
     sys.exit(load_entry_point('chromium-kiosk==0.5.10', 'console_scripts', 'chromium-kiosk')())
   File "/usr/bin/chromium-kiosk", line 22, in importlib_load_entry_point
     for entry_point in distribution(dist_name).entry_points
   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
     return Distribution.from_name(distribution_name)
   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
     raise PackageNotFoundError(name)
 importlib.metadata.PackageNotFoundError: No package metadata was found for chromium-kiosk
```

can you update dependencies so it will work with python3.10?

**Comment by Salamek** [comment]
@pszafer try it now

**Comment by pszafer** [comment]
Will try it tomorrow but looking at dates of pkgs don't you need to rebuild all python-* packages so those will be built against py3.10 as well (python-xscreensaver-config dependency for example)

Thanks for fast response!

**Comment by Salamek** [comment]
@pszafer `python-xscreensaver-config` should be rebuild as well...

**Comment by pszafer** [comment]
@Salamek after upgrade all websites are initially white, don't know why. Chromium process takes 90% CPU, then I need to push F5 and site is loading normally. Any thoughts?

**Comment by Salamek** [comment]
@pszafer try to delete chromium config dir  (/home/chromium-kiosk/.config/chromium)

**Comment by pszafer** [comment]
Unfortunately it doesn't help.
Last week after upgrade to Python3.10 I built package myself and then I did:
```
pacman -S python-pip
pip3 install xscreensaver-config websockets
pacman -U /home/alarm/chromium-kiosk-0.5.10-1-any.pkg.tar.xz
cp /etc/chromium-kiosk/config.yml.pacsave /etc/chromium-kiosk/config.yml
```

After you released your upgrade I did
```
pip3 uninstall xscreensaver-config websockets
pacman -R chromium-kiosk python-pip
```

and installed everything from your repo again.
Since then after startup of chromium-kiosk I got white screen (with 2 chromium processes takes up 90% CPU), after hit F5 everything works again.

**Comment by Salamek** [comment]
@pszafer well in that case i suggest to use install that works for you for now, since i'm planing to do #25 soon....
