### ISSUE TITLE
Error installing: chromium is not installable (Ubuntu 20.04)

### ISSUE THREAD

**Issue by dmartinpro** [Salamek/chromium-kiosk#29]
Unable to install under Ubuntu 20.04.1: it fails with this error message:
chromium-kiosk : Depends: chromium but it is not installable
The reason is simple: chromium is known as 'chromium-browser'

**Comment by Salamek** [comment]
@dmartinpro Hi, you may want to try a manual install for now (mentioned in #28), since i will drop chromium soon #25 (due to bunch of issues with chromium) so i rather focus my time there (#25 will fix this issue too)
