### ISSUE TITLE
Debian 11 (bullseye) Error dependency ttf-dejavu 

### ISSUE THREAD

**Issue by darkol** [Salamek/chromium-kiosk#44]
Hi, I have tried to install on Debian 11 (armhf) but apt fails with unmet dependencies:

`
The following packages have unmet dependencies:
 chromium-kiosk : Depends: ttf-dejavu but it is not installable
E: Unable to correct problems, you have held broken packages.
`

It seems the ttf-dejavu dummy package was dropped in Bullseye as being replaced before Buster with package **fonts-dejavu**

**Comment by darkol** [comment]
I have manually changed dependency ttf-dejavu to fonts-dejavue and it seems install goes ok:

`
$ apt download chromium-kiosk

$ dpkg -x chromium-kiosk_0.5.12-1_all.deb chromium-kiosk
$ dpkg --control chromium-kiosk_0.5.12-1_all.deb chromium-kiosk/DEBIAN
$ vi chromium-kiosk/DEBIAN/control
$ dpkg -b chromium-kiosk chromium-kiosk_0.5.12-1_all_bullseye.deb
dpkg-deb: building package 'chromium-kiosk' in 'chromium-kiosk_0.5.12-1_all_bullseye.deb'.

$ sudo apt install ./chromium-kiosk_0.5.12-1_all_bullseye.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'chromium-kiosk' instead of './chromium-kiosk_0.5.12-1_all_bullseye.deb'
The following additional packages will be installed:
  libjpeg-turbo-progs libmikmod3 libportmidi0 libsdl-mixer1.2 libsdl-ttf2.0-0 libturbojpeg0 python3-docopt python3-numpy python3-pygame python3-websockets python3-xscreensaver-config python3-yaml unclutter unclutter-startup
  xinput xscreensaver xscreensaver-bouncing-text xscreensaver-data xscreensaver-gl
Suggested packages:
  gfortran python-numpy-doc python3-dev python3-numpy-dbg python3-pytest python-pygame-doc timidity fortune gdm3 | kdm-gdmcompat qcam | streamer xdaliclock xfishtank xscreensaver-data-extra xscreensaver-gl-extra
The following NEW packages will be installed:
  chromium-kiosk libjpeg-turbo-progs libmikmod3 libportmidi0 libsdl-mixer1.2 libsdl-ttf2.0-0 libturbojpeg0 python3-docopt python3-numpy python3-pygame python3-websockets python3-xscreensaver-config python3-yaml unclutter
  unclutter-startup xinput xscreensaver xscreensaver-bouncing-text xscreensaver-data xscreensaver-gl
0 upgraded, 20 newly installed, 0 to remove and 95 not upgraded.
Need to get 8,025 kB/11.1 MB of archives.
After this operation, 43.3 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://httpredir.debian.org/debian bullseye/main armhf python3-docopt all 0.6.2-3 [26.6 kB]
Get:2 http://httpredir.debian.org/debian bullseye/main armhf python3-websockets all 8.1-1 [47.7 kB]
Get:3 http://httpredir.debian.org/debian bullseye/main armhf python3-yaml armhf 5.3.1-5 [129 kB]
Get:4 http://httpredir.debian.org/debian bullseye/main armhf xscreensaver-data armhf 5.45+dfsg1-2 [323 kB]
Get:5 /home/olimex/chromium-kiosk_0.5.12-1_all_bullseye.deb chromium-kiosk all 0.5.12-1 [3,038 kB]
Get:6 http://httpredir.debian.org/debian bullseye/main armhf xscreensaver armhf 5.45+dfsg1-2 [610 kB]
Get:7 https://repository.salamek.cz/deb/pub all/main armhf python3-xscreensaver-config all 1.0.6-1 [4,376 B]
Get:8 https://repository.salamek.cz/deb/pub all/main armhf xscreensaver-bouncing-text all 1.1.8-1 [8,024 B]
Get:9 http://httpredir.debian.org/debian bullseye/main armhf unclutter armhf 8-25 [15.1 kB]
Get:10 http://httpredir.debian.org/debian bullseye/main armhf xinput armhf 1.6.3-1 [50.4 kB]
Get:11 http://httpredir.debian.org/debian bullseye/main armhf python3-numpy armhf 1:1.19.5-1 [2,981 kB]
Get:12 http://httpredir.debian.org/debian bullseye/main armhf libportmidi0 armhf 1:217-6 [20.0 kB]
Get:13 http://httpredir.debian.org/debian bullseye/main armhf libmikmod3 armhf 3.3.11.1-6 [119 kB]
Get:14 http://httpredir.debian.org/debian bullseye/main armhf libsdl-mixer1.2 armhf 1.2.12-16+b1 [78.8 kB]
Get:15 http://httpredir.debian.org/debian bullseye/main armhf libsdl-ttf2.0-0 armhf 2.0.11-6 [17.1 kB]
Get:16 http://httpredir.debian.org/debian bullseye/main armhf python3-pygame armhf 1.9.6+dfsg-4+b1 [515 kB]
Get:17 http://httpredir.debian.org/debian bullseye/main armhf xscreensaver-gl armhf 5.45+dfsg1-2 [2,800 kB]
Get:18 http://httpredir.debian.org/debian bullseye/main armhf libturbojpeg0 armhf 1:2.0.6-4 [146 kB]
Get:19 http://httpredir.debian.org/debian bullseye/main armhf libjpeg-turbo-progs armhf 1:2.0.6-4 [125 kB]
Get:20 http://httpredir.debian.org/debian bullseye/main armhf unclutter-startup all 8-25 [8,860 B]
Fetched 8,025 kB in 2s (3,347 kB/s)
Preconfiguring packages ...
Selecting previously unselected package python3-docopt.
(Reading database ... 126843 files and directories currently installed.)
Preparing to unpack .../00-python3-docopt_0.6.2-3_all.deb ...
Unpacking python3-docopt (0.6.2-3) ...
Selecting previously unselected package python3-websockets.
Preparing to unpack .../01-python3-websockets_8.1-1_all.deb ...
Unpacking python3-websockets (8.1-1) ...
Selecting previously unselected package python3-xscreensaver-config.
Preparing to unpack .../02-python3-xscreensaver-config_1.0.6-1_all.deb ...
Unpacking python3-xscreensaver-config (1.0.6-1) ...
Selecting previously unselected package python3-yaml.
Preparing to unpack .../03-python3-yaml_5.3.1-5_armhf.deb ...
Unpacking python3-yaml (5.3.1-5) ...
Selecting previously unselected package xscreensaver-data.
Preparing to unpack .../04-xscreensaver-data_5.45+dfsg1-2_armhf.deb ...
Unpacking xscreensaver-data (5.45+dfsg1-2) ...
Selecting previously unselected package xscreensaver.
Preparing to unpack .../05-xscreensaver_5.45+dfsg1-2_armhf.deb ...
Unpacking xscreensaver (5.45+dfsg1-2) ...
Selecting previously unselected package unclutter.
Preparing to unpack .../06-unclutter_8-25_armhf.deb ...
Unpacking unclutter (8-25) ...
Selecting previously unselected package xinput.
Preparing to unpack .../07-xinput_1.6.3-1_armhf.deb ...
Unpacking xinput (1.6.3-1) ...
Selecting previously unselected package python3-numpy.
Preparing to unpack .../08-python3-numpy_1%3a1.19.5-1_armhf.deb ...
Unpacking python3-numpy (1:1.19.5-1) ...
Selecting previously unselected package libportmidi0:armhf.
Preparing to unpack .../09-libportmidi0_1%3a217-6_armhf.deb ...
Unpacking libportmidi0:armhf (1:217-6) ...
Selecting previously unselected package libmikmod3:armhf.
Preparing to unpack .../10-libmikmod3_3.3.11.1-6_armhf.deb ...
Unpacking libmikmod3:armhf (3.3.11.1-6) ...
Selecting previously unselected package libsdl-mixer1.2:armhf.
Preparing to unpack .../11-libsdl-mixer1.2_1.2.12-16+b1_armhf.deb ...
Unpacking libsdl-mixer1.2:armhf (1.2.12-16+b1) ...
Selecting previously unselected package libsdl-ttf2.0-0:armhf.
Preparing to unpack .../12-libsdl-ttf2.0-0_2.0.11-6_armhf.deb ...
Unpacking libsdl-ttf2.0-0:armhf (2.0.11-6) ...
Selecting previously unselected package python3-pygame.
Preparing to unpack .../13-python3-pygame_1.9.6+dfsg-4+b1_armhf.deb ...
Unpacking python3-pygame (1.9.6+dfsg-4+b1) ...
Selecting previously unselected package xscreensaver-gl.
Preparing to unpack .../14-xscreensaver-gl_5.45+dfsg1-2_armhf.deb ...
Unpacking xscreensaver-gl (5.45+dfsg1-2) ...
Selecting previously unselected package xscreensaver-bouncing-text.
Preparing to unpack .../15-xscreensaver-bouncing-text_1.1.8-1_all.deb ...
Unpacking xscreensaver-bouncing-text (1.1.8-1) ...
Selecting previously unselected package chromium-kiosk.
Preparing to unpack .../16-chromium-kiosk_0.5.12-1_all_bullseye.deb ...
Unpacking chromium-kiosk (0.5.12-1) ...
Selecting previously unselected package libturbojpeg0:armhf.
Preparing to unpack .../17-libturbojpeg0_1%3a2.0.6-4_armhf.deb ...
Unpacking libturbojpeg0:armhf (1:2.0.6-4) ...
Selecting previously unselected package libjpeg-turbo-progs.
Preparing to unpack .../18-libjpeg-turbo-progs_1%3a2.0.6-4_armhf.deb ...
Unpacking libjpeg-turbo-progs (1:2.0.6-4) ...
Selecting previously unselected package unclutter-startup.
Preparing to unpack .../19-unclutter-startup_8-25_all.deb ...
Unpacking unclutter-startup (8-25) ...
Setting up python3-docopt (0.6.2-3) ...
Setting up xscreensaver-data (5.45+dfsg1-2) ...
Setting up libmikmod3:armhf (3.3.11.1-6) ...
Setting up python3-yaml (5.3.1-5) ...
Setting up xinput (1.6.3-1) ...
Setting up libturbojpeg0:armhf (1:2.0.6-4) ...
Setting up python3-xscreensaver-config (1.0.6-1) ...
Setting up libportmidi0:armhf (1:217-6) ...
Setting up unclutter (8-25) ...
update-alternatives: using /usr/bin/unclutter-classic to provide /usr/bin/unclutter (unclutter) in auto mode
Setting up libsdl-mixer1.2:armhf (1.2.12-16+b1) ...
Setting up python3-numpy (1:1.19.5-1) ...
Setting up xscreensaver-gl (5.45+dfsg1-2) ...
Setting up xscreensaver (5.45+dfsg1-2) ...
Setting up libsdl-ttf2.0-0:armhf (2.0.11-6) ...
Setting up unclutter-startup (8-25) ...
Setting up python3-websockets (8.1-1) ...
Setting up libjpeg-turbo-progs (1:2.0.6-4) ...
Setting up python3-pygame (1.9.6+dfsg-4+b1) ...
Setting up xscreensaver-bouncing-text (1.1.8-1) ...
Updating XScreenSaver config...
Updating XScreenSaver config...
Setting up chromium-kiosk (0.5.12-1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/chromium-kiosk_configwatcher.service → /lib/systemd/system/chromium-kiosk_configwatcher.service.
Processing triggers for libc-bin (2.31-13+deb11u2) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for desktop-file-utils (0.26-1) ...
`

**Comment by mishoboss** [comment]
Can we have this quick fix in the original .deb?

**Comment by mishoboss** [comment]
Seems the repo still doesn't have the new deb. A clean install from https://repository.salamek.cz/deb/pub still has this error.
