### ISSUE TITLE
Feature Request: Restart the whole machine on CRON defined time

### ISSUE THREAD

**Issue by mishoboss** [Salamek/chromium-kiosk#49]
Option to restart the whole machine on CRON defined time. Useful to keep the machine clean and working by periodically restarting it.

**Comment by Salamek** [comment]
I think we will leave this as OPT-IN and not implemented any way in this package since setting this up is super simple, i have created HOWTO for it here https://github.com/Salamek/chromium-kiosk/blob/master/.docs/README.md#periodic-reboot
