### ISSUE TITLE
Behind modal dialog

### ISSUE THREAD

**Issue by JuliusTZM** [Salamek/chromium-kiosk#5]
Dera Salamek,

The virtual keyboard feature seems to be buggy a bit. For example when I open the link below:

[link](https://bet.szerencsejatek.hu/?showLogin)

the virtual keyboard shows up behind the login modal dialog.
Are there any workaround or can you please fix it?

Thanks!

**Comment by Salamek** [comment]
@JuliusTZM it should be fixed in latest release
