### ISSUE TITLE
Clear Cookies/Complete Reset (feature request)

### ISSUE THREAD

**Issue by AdamsLab01** [Salamek/chromium-kiosk#58]
I see the option is possibly in qiosk "-i, --idle <seconds>  Timeout to reset" but not sure if it's available in chromium-kiosk... But I'd like there to be an option to have IDLE_TIME not only redirect but also clear all cookies and settings, basically reset the browser.

IDLE_TIME redirects back to the set homepage but does not seem to clear cookies/logins. Example: I can login to Outlook/365 wait for IDLE_TIME to kick/go back to the home page, go back to Outlook/365 and I'm still logged in. 

tnx

**Comment by Salamek** [comment]
@AdamsLab01 should be working in qiosk:1.1.2
