### ISSUE TITLE
PDF doesn't load

### ISSUE THREAD

**Issue by d3dx9** [Salamek/chromium-kiosk#60]
Hi!

It seems like PDFs don't load, it opens the PDF viewer but it simply blacks out better said the content is not displayed. It also only happens with chromium-kiosk and not when running chromium-browser standalone.

Any idea how to fix it?

**Comment by d3dx9** [comment]
Seems to be due to https://chromestatus.com/feature/5669008342777856

**Comment by Salamek** [comment]
@d3dx9 what backend are you using? `chromium-browser` or `chromium` or `qiosk` ?
It works for me with `chromium-browser` as backend, but it does not work in `qiosk`...

**Comment by Salamek** [comment]
* armhf Raspbian latest 
  * not working using `qiosk`
* x86_64 Debian 11
  * not working using `qiosk`
  * working using `chromium`
* x64_64 Archlinux latest
  * working using `chromium`
  * working using `qiosk`

**Comment by Salamek** [comment]
Ok i did some digging and found a bug report
https://bugs.launchpad.net/ubuntu/+source/qtwebengine-opensource-src/+bug/1926089

looks like it was fixed in 5.15.5, but it is broken in 5.15.2 (current debian stable)

**Comment by Salamek** [comment]
Qiosk PDF works only in debian testing>

**Comment by Salamek** [comment]
Well i consider this as fixed?

**Comment by Davis8483** [comment]
> [@d3dx9](https://github.com/d3dx9) what backend are you using? `chromium-browser` or `chromium` or `qiosk` ? It works for me with `chromium-browser` as backend, but it does not work in `qiosk`...

how do I change the backend to use `chromium-browser` instead?

**Comment by Salamek** [comment]
@Davis8483 no longer possible (there is no reason for it), also this issue should be fixed for Debian 12 since qiosk is build using QT6 so you are either using old version or legacy qt5-qiosk (or this bug is back for different reason)

**Comment by Davis8483** [comment]
@Salamek I'm running Raspbian, I would just install the provided Debian image, although I'm running the kiosk on the same Pi that's hosting a web server, and I really don't want to have to re-set up the web server. I found a kiosk chrome extension that seems to provide the same functionality as this repo, so I'll prob just use that. Thanks for the quick response!
