### ISSUE TITLE
Feature Request: Manual reset kiosk app

### ISSUE THREAD

**Issue by darkol** [Salamek/chromium-kiosk#62]
I think chromium_kiosk watch_config could be extended to provide 'config_watcher' client(s) 'event':'onClientAppReset' similar to chrome.idle.onStateChanged idle reset.e.g. for remote reset of the kiosk to homePage (HW Button keypress, some external event etc.) 

Or can be this done already by some other means?
If not, I apply to implement this.

**Comment by Salamek** [comment]
Well i would focus "our" attention to `qiosk` more i want to deprecate `chromium` backend with those crazy TS extensions...
But yes i would like to be able to have two way communication between `qiosk` and client app, to handle events and be able to do custom things...

**Comment by Salamek** [comment]
Hi, this is now possible by using websocket control by calling `setUrl` see https://github.com/Salamek/qiosk/tree/master/.docs#remote-control
