### ISSUE TITLE
Feature Request: Idle / Wakeup websocket API

### ISSUE THREAD

**Issue by darkol** [Salamek/chromium-kiosk#63]
I think it would be interesting to implement Idle / Wakeup websocket API.

For Idle example, when Kiosk (chromium, qiosk?) goes idle, it could send event on its 'config_watcher' websocket connection.
chromium_kiosk 'watch_config' could be extended for 'idle_watcher' client connection(s) and when 'watch_config' receives 'onClientIdle' event from config_watcher, idle_watcher client(s) could be sent the 'onClientIdle' event to do their stuff e.g. shutting down periferals, touch-screen, rfid reader, lights, ....

For the Wakeup/Reset of the kiosk via 'config_watcher' similarly, 'idle_watcher' client(s) could be listened for 'event':'onClientAppReset' based on their custom input e.g. Button press, Motion sensor, Proximity Sensor ... that would be sent to 'config_watcher' client to reset the kiosk app as in https://github.com/Salamek/chromium-kiosk/issues/62

Or can be this done already by some other means?
If not, I apply to implement this.

**Comment by Salamek** [comment]
This websocket comm design ~requires the browser to run websocket server (so multiple clients can connect), but chromium extension is not able to run websocket server... so i would like to do this but in `qiosk` and "phase out" `chromium`

**Comment by Salamek** [comment]
This is done in v1.5 of qiosk see https://github.com/Salamek/qiosk/tree/master/.docs#events
