### ISSUE TITLE
Cannot obtain pre-v1.1 versions of chromium-kiosk from repo to retain compatibility

### ISSUE THREAD

**Issue by Ozzard** [Salamek/chromium-kiosk#67]
The project's repo only contains the 1.1.1 version; no older versions are retained for backwards compatibility.  This makes this project unsuitable for anyone doing automated builds with versioning.  What are the chances of having older versions available in the repo?

**Comment by Salamek** [comment]
reprepo i'm using does not allow multiple versions of same package, only thing i can do is create separate build pipeline for specific tag and rename package to chromium-kiosk1_1.0.7 (if it is worth of effort)?

Anyway here is 1.0.7:
[chromium-kiosk_1.0.7-1_all.zip](https://github.com/Salamek/chromium-kiosk/files/9585668/chromium-kiosk_1.0.7-1_all.zip) (in zip cos github)

**Comment by Ozzard** [comment]
Ah, reprepo :-).  Thanks - I'll work it out from that.
