### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by ambrits** [Salamek/chromium-kiosk#68]
Hi!
Unfortunately, I can't install it on ArcoLinux because I get Python error message at the end.

**Comment by Salamek** [comment]
1) The error message you got would be helpful (well, required for me to help you in any way)...
2) this project should be installed on Linux OS (Debian & Archlinux is supported) without DE (CLI only) it installs required DE & X components it self... as i can see ArcoLinux is full sized desktop OS with DE pre-configured etc... that may get in conflict with some stuff...

**Comment by ambrits** [comment]
Hi!

I tried it on ArchLinux, but the result is same:

(227/227) telepítés: chromium-kiosk                                                                                    [#######################################################################] 100%
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/chromium-kiosk", line 33, in <module>
    sys.exit(load_entry_point('chromium-kiosk==2.0.2', 'console_scripts', 'chromium-kiosk')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/chromium-kiosk", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for chromium-kiosk
Created symlink /etc/systemd/system/multi-user.target.wants/chromium-kiosk_configwatcher.service → /usr/lib/systemd/system/chromium-kiosk_configwatcher.service.
A(z) chromium-kiosk csomag opcionális függőségei:
    xf86-video-fbturbo: Install on Raspberry PI 3 for faster rendering

**Comment by Salamek** [comment]
@ambrits try it now (version 2.0.3 should be installable)

**Comment by ambrits** [comment]
Great! It works. :)
