### ISSUE TITLE
Completely hide mouse cursor when TOUCHSCREEN=true

### ISSUE THREAD

**Issue by mishoboss** [Salamek/chromium-kiosk#73]
By using the default unclutter idle time the mouse cursor is visible for like several seconds after interaction, which on touchscreen is usually undesired behaviour.

I tried `xset -nocursor`, but had no effect for some reason, so I set unclutter with `-idle 0.01`. Which works, but when dragging the cursor is still visible. Ultimately we should start xorg wih completely hidden or invisible cursor (maybe supply a custom cursor icon 1x1 pixel).

**Comment by mishoboss** [comment]
Hey, what about that one? Cursor is ruining the smooth experience :(

**Comment by mishoboss** [comment]
Hey Adam, do you have a roadmap for this one. Would be so much more awesome without cursor on touchscreens.

**Comment by Salamek** [comment]
@mishoboss already released in `chromium-kiosk` 2.5 and `qiosk`  1.8

use configuration option:

```yml
CURSOR:
    ENABLED: false 
```
