### ISSUE TITLE
Hide scrollbars when TOUCHSCREEN=true

### ISSUE THREAD

**Issue by mishoboss** [Salamek/chromium-kiosk#74]
Currently (I guess the default xorg) scrollbars are rendered for vertical and horizontal scrolling. Can they be hidden when touchscreen is true?

**Comment by mishoboss** [comment]
Regarding this one - is it something easy to be done?

**Comment by Salamek** [comment]
Configurable by using:

#SCROLL_BARS:
#  ENABLED: false  # Show hide scroll bars

In chromium-kiosk 2.4 + qiosk 1.7.1
