### ISSUE TITLE
Cookies and/or broswer storage are lost on exit

### ISSUE THREAD

**Issue by roobre** [Salamek/chromium-kiosk#75]
Hello there!

I've been happily using chromium-kiosk to show a Grafana dashboard on an unattended machine. I have also recently set it up on a different machine to serve as a Homeassistant dashboard.

Something I've noticed is that chromium-kiosk would log me out from both sites when the device is rebooted. I'm pretty sure that Homeassistant is storing session data in the browser's local storage, and I'm not positive about Grafana but I bet that one is using cookies.

I think it would be great for those use cases if chromium-kiosk could preserve them across boots, as logging in requires some effort (e.g. I don't have my password manager installed on kiosks) and rebooting may happen more frequently that one might expect, e.g. power cuts.

Is there a way to configure chromium-kiosk to persist cookies/localstorage? If not, would this be something that you could consider implementing? Thanks!

**Comment by roobre** [comment]
In case it helps, I currently have `IDLE_TIME` set to 0:

```
IDLE_TIME: 0 # Seconds, How log must be kiosk idle to redirect to HOME_PAGE, 0=disabled
```

**Comment by misisnik** [comment]
Having the same issue.
In systemctl status: 

`"/usr/lib/qt6/QtWebEngineProcess --type=renderer --webengine-schemes=qrc:sV --first-renderer-process --disable-speech-api --enable-threaded-compositing **--disable-databases**`

could not be this the issue ?

**Comment by Salamek** [comment]
Ok this should be fixed in latest versions, you need to set your profile name in /etc/chromium-kiosk/config.yml like this:

```yml
PROFILE_NAME: 'my-profile'
```

Default profile name is `default` that is by default "off-the-record"

**Comment by roobre** [comment]
This is working wonderfully now, huge thanks @Salamek!
