### ISSUE TITLE
It is not possible to define additional environment variables

### ISSUE THREAD

**Issue by roobre** [Salamek/chromium-kiosk#76]
For certain use cases it is beneficial to be able to set arbitrary environment variables for the X11 session. For example, setting `QT_SCALE_FACTOR` is a very convenient way to make the browser bigger on small touchscreens.

However, I haven't found so far a way to do this other than manually editing `.xinitrc`, which as per the comment on the file is strongly discouraged.

A way to do this would be to allow `.xinitrc` to `source`, instead of exec, `/var/lib/chromium-kiosk/chromium-kiosk-prehook.sh`. This way, the prehook would retain its current functionality but also allow `export`ing env vars which would persist in the X session.

**Comment by roobre** [comment]
As a workaround, I've managed to do this by dropping `export` lines on `/var/lib/chromium-kiosk/.bashrc`, as it happens to be sourced by `.bash_profile` in the same directory.

However as it seems that the latter is on its path to be deprecated (#71) I think the issue is still valid.

**Comment by Salamek** [comment]
Look at https://github.com/Salamek/chromium-kiosk/blob/ba20b4634eb7a95e41c9fcb8ce2028742ddc3c83/chromium_kiosk/bin/chromium_kiosk.py#L324

if you create ~/chromium-kiosk-prehook.sh, it should get run before chromium-kiosk run

**Comment by Salamek** [comment]
.xinitrc should still work after #71 is done, so maybe source chromium-kiosk-prehook.sh as suggested?  and be done with it? PR's welcomed

**Comment by Salamek** [comment]
I have added `EXTRA_ENV_VARS` option to config, see docs
