### ISSUE TITLE
Options for remote control

### ISSUE THREAD

**Issue by vaaski** [Salamek/chromium-kiosk#79]
Hey, I've been using this project sucessfully for years for custom signage, without any keyboard or mouse attached. Sometimes I do need to interact with it tho, and the solution of hooking a keyboard up and standing outside in the cold isn't my favorite.

I am not too familiar with Linux and it's desktops (or lack thereof), is there a way to access the kiosk remotely? With something like VNC maybe?

I've tried setting the REMOTE_DEBUGGING variable to some number (6669) and rebooting, then adding the IP and port into chrome://inspect on my laptop, but it doesn't show up unfortunately. I'm not physically in the same network, but connected over Wireguard, so that might be the issue (although ssh access works fine).

Edit: I've also tried at least taking a screenshot with scrot and xwd, but both say they're unable to open a display.

Thanks.

**Comment by vaaski** [comment]
Finally got around to testing it, thank you so much!
Works almost flawlessly, just had to set the correct permissions on the password file since I kept getting "wrong password" rejections when trying to connect. This fixed it:

```bash
chmod 600 /etc/x11vnc.pwd
chown chromium-kiosk:chromium-kiosk /etc/x11vnc.pwd
```

**Comment by Salamek** [comment]
Great, i added permission change in the doc.
