### ISSUE TITLE
Screen does not go to sleep

### ISSUE THREAD

**Issue by technicallyfeasible** [Salamek/chromium-kiosk#82]
When running this app it prevents the screen from going to sleep.

Is there a config option to control this behavior and be able to turn it off?

I am running a fresh installation using the `qiosk` browser.

**Comment by Salamek** [comment]
Hmm nobody wanted this behaviour, currently it is hardcoded in https://github.com/Salamek/chromium-kiosk/blob/master/var/lib/chromium-kiosk/.xinitrc (`/var/lib/chromium-kiosk/.xinitrc`)

https://github.com/Salamek/chromium-kiosk/blob/6b3667b53fcd8ddbc5428d8aa00cf5a8f86c4b79/var/lib/chromium-kiosk/.xinitrc#L2-L4

So you may comment these out for now...

**Comment by technicallyfeasible** [comment]
thanks for the quick reply. I actually figured out that the main reason my screen didn't go to sleep was that Wayfire disables screen idle when in fullscreen by default.
I had to add this to /etc/wayfire/defaults.ini
```
[idle]
disable_on_fullscreen = false
screensaver_timeout = 10
dpms_timeout = 10
```

**Comment by Salamek** [comment]
Ah you are running qiosk directly under wayland(wayfire) or chromium-kiosk under xwayland?
