### ISSUE TITLE
No Internet

### ISSUE THREAD

**Issue by mishoboss** [Salamek/chromium-kiosk#83]
I finally got proper x86 machines and mainland Linux kernel works fine with displays I have. However when chromium-kiosk opens I see now “No Internet” sign. I use latest Debian 12.5. Funny thing is there’s perfect internet connection - I ping, I install packages, I CURL. I read somewhere that xorg needs networking config or something, which sounds strange to me, but wanted to mention it. 
![IMG_0410](https://github.com/Salamek/chromium-kiosk/assets/1629929/aba0666c-8f3a-44a0-9448-80d3c77bac82)

**Comment by Salamek** [comment]
I have seen this only for a moment (1-2s) after boot on some machines, looks like chromium-kiosk gets loaded before NIC is ready or before locally running web server has started, but it always refreshed for me when NIC status changed/webserver started...  it stays in this offline mode for you like for forever?

**Comment by mishoboss** [comment]
Yes, no change after seconds or minutes. Any way to wait for NIC ready before start?

**Comment by Salamek** [comment]
Hmm weird, i need to reproduce this first... we could wait in systemd unit that autologins the user something like:
```
After=network-online.target
Wants=network-online.target
```

But chromium kiosk should reload automatically when it detect internet connection... Do you use any unusually network configuration (Static IPs, proxy, etc...)?

**Comment by mishoboss** [comment]
No, nothing exotic - DHCP, no proxy.

It’s latest Debian - 12.5. Minimal server, no GUI.

**Comment by mishoboss** [comment]
I’ve just tested on another Ethernet network (not in my home), just to exclude the network part of the equation. It’s the same result. I believe it’s something in the latest Debian. Have you tried 12.5?

**Comment by Salamek** [comment]
I just tested it in virtual machine, Debian 12.5 from https://gemmei.ftp.acc.umu.se/debian-cd/current/amd64/iso-cd/debian-12.5.0-amd64-netinst.iso

chromium-kiosk installed by steps (copy/paste) from https://github.com/Salamek/chromium-kiosk/tree/master/.docs
reboot:
![Screenshot_20240328_182849](https://github.com/Salamek/chromium-kiosk/assets/1226241/f0272771-7954-4957-be3f-8bbed27cb03f)

(it works fine, that is page on Internet https://salamek.github.io/chromium-kiosk/)

**Comment by Salamek** [comment]
And i doubt i will get different result on real HW... (but i will test it there if you will insist :-))

**Comment by mishoboss** [comment]
Do you go thru the install steps with sudo or as a root user?

**Comment by Salamek** [comment]
as root

**Comment by mishoboss** [comment]
I’m really shooting in the dark now… :(

**Comment by Salamek** [comment]
Hmm would you be capable and willing to setup SSH access to your chromium-kiosk running machine so i can have a look? i can provide my ssh pub key to you by email or you can generate a new pair/use password auth and send me a access info on email?
Also would be good for it to not contain any sensitive data etc ofc...

**Comment by mishoboss** [comment]
You have a mail. :)

**Comment by Salamek** [comment]
@mishoboss is this solved then?

**Comment by mishoboss** [comment]
Yes, huge thanks for the help!

**Comment by mishoboss** [comment]
@Salamek , actually I was too fast and it's not solved.

Here is what happens:
1. On boot there's the "No internet" sign. Always, no matter which URL is stated (private IP or public domain, doesn't matter).
2. On `/etc/chromium-kiosk/config.yml` edit it picks correctly changed URL and loads it. Immediately after config.yml is saved - page is properly rendered on screen.
3. On reboot - "No internet" sign.
