### ISSUE TITLE
Error running chromium-kiosk

### ISSUE THREAD

**Issue by FedericoDeBona** [Salamek/chromium-kiosk#84]
I've installed successfully chromium-kiosk, this are the system specs:
```bash
$ uname -a  
Linux biiond-NUC13ANHi7 5.15.0-107-generic #117~20.04.1-Ubuntu SMP Tue Apr 30 10:35:57 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ dpkg -l | grep iosk
ii  chromium-kiosk                             2.3.0-1                               all          Chromium Kiosk
ii  qt5-qiosk                                  1.7.1                                 amd64        QT Kiosk is simple kiosk browser written in QT
```
I did not change the config file.
`$ sudo chromium-kiosk watch_config` gives
```
Traceback (most recent call last):
  File "/usr/bin/chromium-kiosk", line 33, in <module>
    sys.exit(load_entry_point('chromium-kiosk==2.3.0', 'console_scripts', 'chromium-kiosk')())
  File "/usr/lib/python3/dist-packages/chromium_kiosk/__main__.py", line 5, in main
    _main()
  File "/usr/lib/python3/dist-packages/chromium_kiosk/bin/chromium_kiosk.py", line 308, in main
    getattr(command, 'chosen')()  # Execute the function specified by the user.
  File "/usr/lib/python3/dist-packages/chromium_kiosk/bin/chromium_kiosk.py", line 283, in watch_config
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3/dist-packages/chromium_kiosk/bin/chromium_kiosk.py", line 274, in main
    async for websocket in websockets.connect(uri):
TypeError: 'async for' requires an object with __aiter__ method, got Connect
```
Running `$ sudo chromium-kiosk run` the output is
```
xrandr: Failed to get size of gamma for output default
xrandr: Failed to get size of gamma for output default
/usr/bin/qiosk: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/qiosk)
/usr/bin/qiosk: /lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.15' not found (required by /usr/bin/qiosk)
```
about the xrandr error I've always had it when trying to change the display orientation with this system configuration.

Am I missing something?

**Comment by FedericoDeBona** [comment]
Resolved with ```sudo strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5```, now I get ```Command '['xrandr', '--listactivemonitors']' returned non-zero exit status 1``` probably because of ```xrandr: Failed to get size of gamma for output default``` error

**Comment by Salamek** [comment]
Wow that is kinda old OS... Ubuntu 20.04.1 is from 2020!  is there any reason why wont you upgrade to latest Ubuntu LTS or Debian 12?  So you can use qt6 version of qiosk and don't need to do that ugly `strip` hack, also i think newer version of OS would fix that `watch_config` error and maybe the `xrandr` error too who knows...

**Comment by FedericoDeBona** [comment]
No reasons actually, so now I'm trying with 22.04 LTS on a VM (since right now I don't have a machine that can be upgraded, is it a problem?) with aarch64. 
```
$ sudo chromium-kiosk run
/usr/bin/qiosk: /lib/aarch64-linux-gnu/libQt6Core.so.6: version `Qt_6.4' not found (required by /usr/bin/qiosk)
```
libQt6Core is installed, but the 6.2.4 version
```
$ ls -l /lib/aarch64-linux-gnu/libQt6Core.so*
lrwxrwxrwx 1 root root      15 May  2  2022 /lib/aarch64-linux-gnu/libQt6Core.so -> libQt6Core.so.6
lrwxrwxrwx 1 root root      19 May  2  2022 /lib/aarch64-linux-gnu/libQt6Core.so.6 -> libQt6Core.so.6.2.4
-rw-r--r-- 1 root root 5054592 May  2  2022 /lib/aarch64-linux-gnu/libQt6Core.so.6.2.4
```

**Comment by Salamek** [comment]
Hmm qiosk deb package targets Debian 12 (and derivatives from it), Ubuntu 22.04 LTS should be on par with Debian 12 but for some reason it has older QT6 packages (Maybe their ARM 64 version is not updated that periodically?)

Possible solutions:
* make sure that install is up to date (apt update && apt full-upgrade)
* or look if those packages can't be updated from some backports repo or something
* or get correct version of lib somewhere and use LD_LIBRARY_PATH before running qiosk to load those instead...
*  or use your strip hack
* or try debian 12  
* or force me to create whole Ubuntu build pipeline and repository (not going to happen lol, i don't have time, sorry)

**Comment by FedericoDeBona** [comment]
> * or force me to create whole Ubuntu build pipeline and repository

Since you don't want to **invest** time in this wonderful idea for a VM with aarch64 I'm forced to wait to have a real x86_64 device with the latest ubuntu.

Jokes aside, thank you for time and for this project ❤️

**Comment by Salamek** [comment]
BTW why aarch64 vm? You have ARM workstation? Apple M? (Just curious)
(i would personally try Debian 12 aarch64, its like Ubuntu but without bullshit :-) )

**Comment by FedericoDeBona** [comment]
It's the default image for ubuntu 22.04 for [UTM](https://mac.getutm.app/gallery/ubuntu-20-04) for the Apple M1.


> i would personally try Debian 12 aarch64, its like Ubuntu but without bullshit

not enough into this to know what you are talking about ahah

**Comment by Salamek** [comment]
Ah ok, BTW debian is this https://mac.getutm.app/gallery/debian-12
