### ISSUE TITLE
unmet dependencies

### ISSUE THREAD

**Issue by NikoCherednik** [Salamek/chromium-kiosk#86]
Hi, 
I'm not fo familiar with Linux, so please forgive me if the solution is something obvious ) 
When I run 
`apt install chromium-kiosk`

I get the following error message

```
The following packages have unmet dependencies:
 chromium-kiosk : Depends: python3-docopt but it is not installable
                  Depends: qiosk but it is not going to be installed or
                           qt5-qiosk but it is not going to be installed or
                           qt6-qiosk but it is not going to be installed
                  Depends: unclutter but it is not installable
                  Depends: xinput but it is not installable
E: Unable to correct problems, you have held broken packages.
```

I tried Debian 11.9 and Debian 12, got the same results. What am I missing ?

**Comment by Salamek** [comment]
Hi, i just tested it installing Debian 12.5.0-amd64-netinst.iso and fallowing docs https://github.com/Salamek/chromium-kiosk/tree/master/.docs#debian from 1.-6. 
And it worked fine... did you run `apt update` before running `apt install` ?

**Comment by NikoCherednik** [comment]
Hi,
`12.5.0-amd64-netinst.iso`
Looks like there was the issue, I tried 
`debian-12.5.0-amd64-DVD-1`
I currently don't understand the difference, but I seams there is one. Now everything installed just fine, thank you =) 

Are there any additional steps in the setup process ? Currenty I get to the usual Logon screen in Debian.

**Comment by Salamek** [comment]
Yop, ill mention that in the docs...
