### ISSUE TITLE
Developer console

### ISSUE THREAD

**Issue by NikoCherednik** [Salamek/chromium-kiosk#87]
Hi,
Is there any way to eable DevConsole for Chromium ? 

And a second question: how can I manually reload the page ? Currently I get the problem when I boot up my device, the kiosk get started sooner then an Internet connection is established, soI have to go to the config file and change the homepage, then it reloads, and change it back

**Comment by Salamek** [comment]
You can enable remote debugging and then connect from chromium/chrome browser dev console see: https://github.com/Salamek/chromium-kiosk/blob/master/.docs/README.md#remote-debugging

Remote control docs: https://github.com/Salamek/qiosk/tree/master/.docs#remote-control
Example python script CLI interface for remote control https://github.com/Salamek/chromium-kiosk/blob/master/examples/qiosk-control.py

Browser starting before connection is a bug, tracked in #88

**Comment by Salamek** [comment]
#88 is resolved so i guess this can be closed too then
