### ISSUE TITLE
Extra Argument configuration SCALE page

### ISSUE THREAD

**Issue by itpcss** [Salamek/chromium-kiosk#89]
I tried to use the parameter EXTRA_ARGUMENTS to scale the page with the parameter "--force-device-scale-factor=1.3" but there is no result. Tell me how to scale a running page?

![111](https://github.com/Salamek/chromium-kiosk/assets/25006833/65bb4464-0340-4ee3-84cd-56b3fc10ca34)

As you can see, this parameter is present at startup, but the page does not scale, but the page can be manually scaled, but you need to do it automatically at startup on 130 %

![2222](https://github.com/Salamek/chromium-kiosk/assets/25006833/bcd1af69-7bbf-4cc3-bd6f-cf88482b301c)

**Comment by Salamek** [comment]
Qiosk (a chromium based kiosk first browser we actually use) is written in QT so instead try using:

```yml
EXTRA_ENV_VARS:
    QT_SCALE_FACTOR: 1.3
```

**Comment by itpcss** [comment]
Added this parameter to the configuration file
![000](https://github.com/Salamek/chromium-kiosk/assets/25006833/2144d1da-20bd-4ce5-b6e6-0e72f9c9e9fd)

I get an error at startup

![00000](https://github.com/Salamek/chromium-kiosk/assets/25006833/eeb94b37-4f24-4292-b8a8-67571091acf9)

**Comment by Salamek** [comment]
Oh to hotfix that use '1.3' (string) instead of 1.3 (float) in configuration, in meantime i will add string cast fix in the code...

**Comment by itpcss** [comment]
Thanks for the prompt response. Everything worked as it should. Perhaps someone will also need this information.

**Comment by Salamek** [comment]
I have added info into docs https://github.com/Salamek/chromium-kiosk/blob/master/.docs/README.md#force-scale-factor
