### ISSUE TITLE
page reloads ever few seconds

### ISSUE THREAD

**Issue by euphorah** [Salamek/chromium-kiosk#90]
### problem
page auto-refreshes 
(crashing? would crashing go back to HOME_PAGE? it refreshes on whichever page was clicked on)

### configuration
same issue occurs with debian (12.6.0-amd64-netinst.iso) & archinstall (archlinux-2024.07.01-x86_64) minimum installs over 15 reinstall attempts with various configurations over the past week

attempted window managers: cage (archlinux, debian) & xorg (archlinux)

### janky unfit solution (all via ssh)
change password for chromium-kiosk
login as chromium-kiosk
chromium-kiosk run
no more auto-refreshing

think this might be something im doing wrong?

**Comment by Salamek** [comment]
Can you please post your config.yml?

**Comment by Salamek** [comment]
Also it is possible that this change causes this issue? https://github.com/Salamek/qiosk/commit/2c9ecb0628d6058282b6cbe3a5c716fbb1bcb87c 

Can you try with qiosk 1.7.1? I have uploaded packaged for your distros to release https://github.com/Salamek/qiosk/releases/tag/1.7.1

**Comment by euphorah** [comment]
resolved, thank you (except new issue introduced described below)

`sudo pacman -Sy wget`

`wget https://github.com/Salamek/qiosk/releases/download/1.7.1/qiosk-1.7.1-1-x86_64.pkg.tar.zst`

`sudo pacman -U qiosk-1.7.1-1-x86_64.pkg.tar.zst`

----

first reboot worked fine; subsequent reboots ERR_INTERNET_DISCONNECTED

janky solution enable NAV_BAR, manually press refresh

---

all my troubleshooting config.yml starts fresh with [default](https://github.com/Salamek/chromium-kiosk/blob/8fb3ac59c197972e7df842b9924d1700a62fe456/etc/chromium-kiosk/config.yml)

[default landing page](https://salamek.github.io/chromium-kiosk/) auto reload isn't noticeable until clicking [View on GitHub](https://github.com/Salamek/chromium-kiosk) which exhibits similar behavior to majority of the web

**Comment by Salamek** [comment]
I was able to replicate your issue... fix incoming...

**Comment by Salamek** [comment]
@euphorah qiosk 1.8.1 should fix this issue, please update and let me know if it is ok, THX!

**Comment by euphorah** [comment]
> qiosk 1.8.1 should fix this issue

both issues resolved, thank you
(tested by updating packages and again with a fresh archlinux install)
