### ISSUE TITLE
ENABLED_BUTTONS array doesn't work

### ISSUE THREAD

**Issue by iHamsin** [Salamek/chromium-kiosk#93]
Hello

Thank you for your project!
I tried to disable all buttons except RELOAD:
  ENABLED_BUTTONS: ['reload']
Unfortunately it doesn't work after lots or tries
Please advice me, what I doing wrong?

**Comment by Salamek** [comment]
@iHamsin should be working in `chromium-kiosk` 2.6 and `qiosk` 1.9

**Comment by iHamsin** [comment]
Thank you! You are great!
