### ISSUE TITLE
Disable cache\cookie wipe

### ISSUE THREAD

**Issue by simonyel** [Salamek/chromium-kiosk#94]
Good day,
I'm attempting to use this package to repurpose a tablet into a control panel for home automation. The web interface requires a login, and on every panel reboot, I need to re-authenticate. What would I need to do to disable the clean state on reboot?

**Comment by Salamek** [comment]
Set profile name in your `config.yml` to something different than `default`, for example:
```yml
PROFILE_NAME: 'myprofile'
```

(default profile name is `default` and `default` profile is off-the-books profile)
