### ISSUE TITLE
Problem with reCAPTCHA in the Polish language

### ISSUE THREAD

**Issue by Manius71** [Salamek/chromium-kiosk#97]
I have what might be a somewhat unusual problem with your kiosk. I want to use it with a physical keyboard to provide access to one specific website in Polish. For this purpose, I installed Debian with support for that language, and generally, everything works correctly with your solution after some adjustments. The problem is that on one of the subpages for changing the user's password, reCAPTCHA is used, which unfortunately is displayed in English (the well-known 'I'm not a robot'). A few years ago, I made a similar kiosk using Chromium, and at that time, installing the chromium-l10n package helped solve this issue. In your project, that solution won’t work for obvious reasons. Do you have any idea how to resolve this problem?

**Comment by Salamek** [comment]
This shoud be fixed in `qiosk 1.11.1`,  `Accept-Language` header was not set, now it uses system/user default language or you can force header value by providing  --accept-language en-US to `qiosk` (you can pass that in EXTRA_ARGUMENTS config option of `chromium-kiosk`)

**Comment by Manius71** [comment]
Works flawlessly. Thank you.
